image: "ruby:2.3"

services:
  - rethinkdb:latest

stages:
  - lint
  - test
  - post-test

before_script:
  - sh ./scripts/install-node.sh
  - gem install bundler         # Bundler is not installed with the image
  - gem install rubocop         # Install rubocop globally
  - bundle install -j $(nproc)  # Install dependencies

rubocop:
  stage: lint
  script:
  - rubocop
  tags:
  - docker

rspec:
  variables:
    RETHINKDB_URL: 'rethinkdb://rethinkdb:28015/fireplace_test'
  stage: test
  script:
  - bundle exec rspec
  tags:
  - docker
