# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SeverityLevelsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # SeverityLevel. As you add validations to SeverityLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SeverityLevelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all severity_levels as @severity_levels' do
      severity_level = SeverityLevel.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:severity_levels)).to eq([severity_level])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested severity_level as @severity_level' do
      severity_level = SeverityLevel.create! valid_attributes
      get :show, { id: severity_level.to_param }, valid_session
      expect(assigns(:severity_level)).to eq(severity_level)
    end
  end

  describe 'GET #new' do
    it 'assigns a new severity_level as @severity_level' do
      get :new, {}, valid_session
      expect(assigns(:severity_level)).to be_a_new(SeverityLevel)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested severity_level as @severity_level' do
      severity_level = SeverityLevel.create! valid_attributes
      get :edit, { id: severity_level.to_param }, valid_session
      expect(assigns(:severity_level)).to eq(severity_level)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new SeverityLevel' do
        expect do
          post :create, { severity_level: valid_attributes }, valid_session
        end.to change(SeverityLevel, :count).by(1)
      end

      it 'assigns a newly created severity_level as @severity_level' do
        post :create, { severity_level: valid_attributes }, valid_session
        expect(assigns(:severity_level)).to be_a(SeverityLevel)
        expect(assigns(:severity_level)).to be_persisted
      end

      it 'redirects to the created severity_level' do
        post :create, { severity_level: valid_attributes }, valid_session
        expect(response).to redirect_to(SeverityLevel.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved severity_level as @severity_level' do
        post :create, { severity_level: invalid_attributes }, valid_session
        expect(assigns(:severity_level)).to be_a_new(SeverityLevel)
      end

      it "re-renders the 'new' template" do
        post :create, { severity_level: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested severity' do
        severity_level = SeverityLevel.create! valid_attributes
        put :update, {
          id: severity_level.to_param, severity_level: new_attributes
        }, valid_session
        severity_level.reload
      end

      it 'assigns the requested severity_level as @severity_level' do
        severity_level = SeverityLevel.create! valid_attributes
        put :update, { id: severity_level.to_param, severity_level: valid_attributes },
            valid_session
        expect(assigns(:severity_level)).to eq(severity_level)
      end

      it 'redirects to the severity_level' do
        severity_level = SeverityLevel.create! valid_attributes
        put :update, { id: severity_level.to_param, severity_level: valid_attributes },
            valid_session
        expect(response).to redirect_to(severity_level)
      end
    end

    context 'with invalid params' do
      it 'assigns the severity_level as @severity_level' do
        severity_level = SeverityLevel.create! valid_attributes
        put :update, { id: severity_level.to_param, severity_level: invalid_attributes },
            valid_session
        expect(assigns(:severity_level)).to eq(severity_level)
      end

      it "re-renders the 'edit' template" do
        severity_level = SeverityLevel.create! valid_attributes
        put :update, { id: severity_level.to_param, severity_level: invalid_attributes },
            valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested severity_level' do
      severity_level = SeverityLevel.create! valid_attributes
      expect do
        delete :destroy, { id: severity_level.to_param }, valid_session
      end.to change(SeverityLevel, :count).by(-1)
    end

    it 'redirects to the severity_levels list' do
      severity_level = SeverityLevel.create! valid_attributes
      delete :destroy, { id: severity_level.to_param }, valid_session
      expect(response).to redirect_to(severity_levels_url)
    end
  end
end
